### ISSUE TITLE
Support for supplying default values 

### ISSUE THREAD

**Issue by anubhavmalik** [hitanshu-dhawan/PojoPreferences#1]
It looks really great! The option of supplying a default value for each type would make it just perfect! 👍 

Also are pull request welcome? 🍡 ⭐️

**Comment by hitanshu-dhawan** [comment]
Yes, the ability to mention default values with your Prefs is planned for the next version.
Not sure how to go for this as annotations don't allow `Object` to be its element.
`Object` because default value types will be different for `int`, `String`, `float` etc.
```
public @interface Pref {
    Object defValue();
}
```
This is not allowed. https://stackoverflow.com/q/1458535

Any thoughts on how to solve this?

And yes, pull requests are most welcomed :)

**Comment by hitanshu-dhawan** [comment]
Got it! We can get the value of a variable at compile time if it is marked as `final`.
https://stackoverflow.com/questions/35918511/get-static-field-value-using-annotation-processing

Added the ability to mention default values with your Prefs in this commit https://github.com/hitanshu-dhawan/PojoPreferences/commit/cb8ea5cb44b83112d27bea632f1c6e4a3def0853

Now we can add default values to variables like this
```
@Pojo
public class Data {
    @Pref
    private int a; // no default value
    @Pref
    private final int b = 7; // default value is 7
}
```

**Comment by anubhavmalik** [comment]
That was fast :D
